#!/usr/bin/env python3
"""Sync SKILL.md content into Copilot instructions and Windsurf rules format."""

from __future__ import annotations

import argparse
from pathlib import Path

from validate_content import read_text, FRONTMATTER_DELIMITER


def extract_body(path: Path) -> tuple[dict[str, str], str]:
    lines = read_text(path).splitlines()
    if not lines or lines[0] != FRONTMATTER_DELIMITER:
        return {}, ""
    try:
        close_index = lines.index(FRONTMATTER_DELIMITER, 1)
    except ValueError:
        return {}, ""
    fields = {}
    for line in lines[1:close_index]:
        if ":" in line:
            k, v = line.split(":", 1)
            fields[k.strip()] = v.strip().strip('"').strip("'")
    body = "\n".join(lines[close_index + 1:])
    return fields, body


def generate_copilot_instructions(repo_root: Path) -> str:
    lines = [
        "# GitHub Copilot Project Instructions",
        "",
        "This file is auto-generated by `python scripts/sync_vendor_rules.py`.",
        "It contains project-specific skills and standards from `indium-agentkit`.",
        "",
    ]
    for skill_file in sorted((repo_root / "skills").glob("*/SKILL.md")):
        fields, body = extract_body(skill_file)
        name = fields.get("name", skill_file.parent.name)
        desc = fields.get("description", "")
        lines.append(f"## Skill: {name}")
        lines.append(f"*{desc}*")
        lines.append("")
        lines.append(body.strip())
        lines.append("")
        lines.append("---")
        lines.append("")
    return "\n".join(lines)


def generate_windsurf_rules(repo_root: Path) -> str:
    lines = [
        "# Windsurf Global Rules",
        "",
        "Auto-generated by `python scripts/sync_vendor_rules.py`.",
        "",
    ]
    for skill_file in sorted((repo_root / "skills").glob("*/SKILL.md")):
        fields, _ = extract_body(skill_file)
        name = fields.get("name", skill_file.parent.name)
        desc = fields.get("description", "")
        lines.append(f"### {name}")
        lines.append(f"{desc}")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync skills into Copilot and Windsurf vendor configurations.")
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
        help="Repository root",
    )
    args = parser.parse_args()
    root = args.repo_root.resolve()

    copilot_file = root / ".github" / "copilot-instructions.md"
    copilot_file.parent.mkdir(parents=True, exist_ok=True)
    copilot_file.write_text(generate_copilot_instructions(root), encoding="utf-8")
    print(f"generated {copilot_file}")

    windsurf_file = root / ".windsurfrules"
    windsurf_file.write_text(generate_windsurf_rules(root), encoding="utf-8")
    print(f"generated {windsurf_file}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
